EXECUTABLE	:= cudaCuts
CUFILES		:= Example.cu
CCFILES		:= \
#	imageWrite.cpp
	
#CU_DEPS := CudaCuts.cu edgeWeight.cu PushRelabel_kernel.cu Bfs_kernel.cu
SMVERSIONFLAGS  := -arch sm_11
SMVERSIONFLAGS  := -arch sm_12

include ../../common/common.mk
